### ISSUE TITLE
v1.9.6 (9adad36)

### ISSUE THREAD

**Issue by linkzoid** [thammanna/osticket-slack#2]
Does this support 1.9.6?
It's not showing up for me in add new plugins.

**Comment by thammanna** [comment]
I'm using with osTicket (v1.9.4). Haven't tried with 1.9.6.

**Comment by Rthierry** [comment]
Hello,

I can confirm it works with 1.9.7 on Linux SLES 11.

Thierry

**Comment by linkzoid** [comment]
Did you just clone the git and move the files into include/plugins like instructed?
I can see other plugins fine, but not this one.

> admin@OsTicket:/opt/osticket/include/plugins/slack$ ls
> config.php  plugin.php  slack.php

**Comment by thammanna** [comment]
Clone and move the files into include/plugins. Do check on the permissions.

My directory structure looks as below. 
![capture](https://cloud.githubusercontent.com/assets/1535630/7563568/00ced1b6-f7fc-11e4-94c7-803b559a459f.PNG)

**Comment by linkzoid** [comment]
hrm. We have the same permissions and folder structure yet it's not showing up.
It should be here right? see picture
![a8bxsda](https://cloud.githubusercontent.com/assets/12392997/7564176/68021aea-f7e4-11e4-9472-d145e6a4b57b.png)

I guess it's a error in my osTicket installation.

**Comment by Rthierry** [comment]
It seems to be a right issue

here is mine… but Linux

Only the group has execute et read right.

Thierry

**Comment by linkzoid** [comment]
I had a broken symlink, fixed it now and it works.
Thank you
