### ISSUE TITLE
integration issue on 1.9.6

### ISSUE THREAD

**Issue by anupvarghese** [thammanna/osticket-slack#4]
Plugin is not working on 1.9.6. I am able to add the hook & enable it. But doesn't show any alert on ticket creation (email and support portal)

**Comment by Arnok13** [comment]
Hi i'm still having this problem with 1.9.12

**Comment by suyashjain** [comment]
i too having the same issue with 1.9.12, plugin is installed, The plugin hit the URL as i can see in web server access logs but the query string only contains no "1" (one).

**Comment by achennuru** [comment]
People having issues with the plugin, you could try changing this code after installing the plugin, I managed to put some logs and could figure out why it was not working.

Change the bootstrap to the following. I couldn't get the ticket subscription to work, so subscribing to all events.
`function bootstrap() {
        Signal::connect('model.created', array($this, 'onTicketCreated'));
    }`
In the onTicketCreated method add the following
`if (!($ticket instanceof DynamicFormEntryAnswer)) {
                $this->logMessage(get_class($ticket));
                return;
            }`
Also the field values is not straight forward to get from DynamicFormEntryAnswer, you will have to use its own methods to access the data.

Good luck.
